# backend/engine_adapter.py
"""
Integration seam between the React UI's HTTP contract and the backend team's
audio engine (``cranbrook-audio-project``, aka "hatci-audio-mixer").

The UI posts a rich payload to ``POST /generate`` (see ui/src/payload.js):

    {
      scenario_id, snr_db, speaker_position, seed, car_model,
      driving: 0..3, window: 0..3, venting: 0..3,
      overlays: [{ name, gain?, offset?, location?, velocity? }, ...]
    }

The engine team did NOT build a web service; they built importable DSP:
``mixer.mix_audio(tracks, target_sr)`` mixes N ``(audio, offset_s, gain_db)``
tracks, and ``transform.transform(...)`` does Doppler + binaural HRTF. This
module is the glue: it resolves the payload to real WAV files, builds the
track list, and runs the REAL engine mix. ``backend/app.py`` calls
``generate_from_payload`` and keeps its existing HTTP shape unchanged.

Design choices for this first integrated version:
  * Canonical pipeline rate = 16 kHz mono (matches the existing scenario data
    and metadata; the UI plays whatever WAV it's handed).
  * ``driving`` / ``window`` / ``venting`` actually SELECT samples from raw/
    (the file names encode speed/window/vent), so the UI sliders finally move
    the output. Missing files degrade gracefully (the layer is skipped, never
    a crash).
  * Spatial overlays try the engine's binaural ``transform`` if its native SAF
    library is available; otherwise they fall back to a cheap constant-power
    stereo pan so directional sounds are still lateralized on Windows without
    the CMake/OpenBLAS build.
"""
import os
import re
import sys
import json
import types
import glob
import importlib.util
from datetime import datetime

import numpy as np
import soundfile as sf

# ---------------------------------------------------------------------------
# Reuse the existing generator helpers (mono load+resample, RMS norm, IR, clip)
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
_GENERATOR_DIR = os.path.join(_HERE, "generator")
if _GENERATOR_DIR not in sys.path:
    sys.path.insert(0, _GENERATOR_DIR)

from generator.audio_io import load_wav, normalize_rms, prevent_clipping, apply_cabin_ir  # noqa: E402

from superimposition import noise_superimposition

TARGET_SR = 16000          # canonical pipeline rate (audio_io.load_wav resamples to this)
SPEECH_RMS_DB = -20.0      # reference level everything is mixed relative to

_REPO_ROOT = os.path.abspath(os.path.join(_HERE, ".."))
_ENGINE_ROOT = os.path.join(_REPO_ROOT, "cranbrook-audio-project")
_DATA_ROOT = os.path.join(_REPO_ROOT, "data")

# ---------------------------------------------------------------------------
# Inter-team CONTRACT #1: overlay sound_id -> sample file under raw/.
#
# Covers all 15 ids in the UI's sound_library.js. baby_crying / people_talking
# use real recordings; the rest currently point at PROCEDURAL PLACEHOLDERS in
# raw/distributed/sfx/ (generated by backend/make_placeholder_sfx.py) so the
# whole catalog is audible for demos. Replace a placeholder by dropping a real
# recording at the same path — no code change needed. Unmapped ids are skipped
# with a logged warning.
# ---------------------------------------------------------------------------
SOUND_FILE_MAP = {
    # Real recordings
    "baby_crying": "distributed/background/Crying1.wav",
    "people_talking": "distributed/speech/Talking2.wav",
    # Placeholders (replace with real recordings when sourced)
    "rain": "distributed/sfx/rain.wav",
    "hail": "distributed/sfx/hail.wav",
    "wind": "distributed/sfx/wind.wav",
    "thunder": "distributed/sfx/thunder.wav",
    "snow": "distributed/sfx/snow.wav",
    "phone_ringing": "distributed/sfx/phone_ringing.wav",
    "music": "distributed/sfx/music.wav",
    "coughing": "distributed/sfx/coughing.wav",
    "car_passing": "distributed/sfx/car_passing.wav",
    "emergency_siren": "distributed/sfx/emergency_siren.wav",
    "motorcycle": "distributed/sfx/motorcycle.wav",
    "truck_horn": "distributed/sfx/truck_horn.wav",
    "construction": "distributed/sfx/construction.wav",
}

# CONTRACT #2: UI driving level (0..3) -> road-noise speed bucket in raw/noise.
# Available speeds: s0, s40, s50, s60, s70, s100, s110.
_DRIVING_TO_SPEED = {0: "s0", 1: "s25", 2: "s45", 3: "s70"}


# ---------------------------------------------------------------------------
# Lazy load of the engine's mixer (importable mix_audio lives in the engine repo)
# ---------------------------------------------------------------------------
_mixer_mod = None


def _load_mixer():
    """Import mixer.mix_audio from the engine repo by file path.

    mixer.py does ``import librosa`` at module top but only uses it in its CLI
    main(); the importable ``mix_audio`` does not. librosa has no wheels on this
    env's Python yet, so we install an empty stub module ONLY when it's missing,
    letting the genuine engine code import and run for the core mix path.
    """
    global _mixer_mod
    if _mixer_mod is not None:
        return _mixer_mod

    if importlib.util.find_spec("librosa") is None and "librosa" not in sys.modules:
        sys.modules["librosa"] = types.ModuleType("librosa")

    path = os.path.join(_ENGINE_ROOT, "mixer", "mixer.py")
    if not os.path.exists(path):
        raise FileNotFoundError(f"engine mixer not found at {path}")
    spec = importlib.util.spec_from_file_location("cranbrook_mixer", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    _mixer_mod = module
    return module


# ---------------------------------------------------------------------------
# File-resolution helpers (all degrade gracefully to None)
# ---------------------------------------------------------------------------
def _raw(*parts):
    return os.path.join(_REPO_ROOT, "raw", *parts)


def _first_existing(*candidates):
    """Return the first candidate path that exists, else None."""
    for c in candidates:
        if c and os.path.exists(c):
            return c
    return None


def _swap_window_suffix(filename, window):
    """Rewrite a ``..._w{N}.wav`` file name to the requested window state."""
    return re.sub(r"_w\d(?=\.wav$)", f"_w{window}", filename)


def _select_road_noise(driving, window):
    """Pick a road-noise sample for the given driving/window, or None."""
    speed = _DRIVING_TO_SPEED.get(int(driving), "s50")
    if speed == "s0" and int(driving) == 0:
        # At rest: no road noise layer.
        return None
    base = _raw("distributed", "noise")
    # Try exact, then any window for that speed, then any ver-suffixed variant.
    exact = os.path.join(base, f"{speed}_w{window}.wav")
    by_speed = sorted(glob.glob(os.path.join(base, f"{speed}_w*.wav")))
    return _first_existing(exact, *(by_speed or []))


def _select_ventilation(venting, window):
    """Pick a ventilation sample for the given vent level, or None."""
    if not venting:
        return None
    base = _raw("distributed", "ventilation")
    # Vent files only exist for w0 / w2; snap the window to the nearest.
    snapped = 0 if int(window) < 2 else 2
    cand = os.path.join(base, f"v{int(venting)}_w{snapped}.wav")
    any_v = sorted(glob.glob(os.path.join(base, f"v{int(venting)}_w*.wav")))
    return _first_existing(cand, *(any_v or []))


def _resolve_cabin_ir(scenario, window):
    """Resolve the cabin IR path, swapping its window suffix to match the UI."""
    ingredients = scenario.get("audio_ingredients", {})
    ir = ingredients.get("cabin_ir", {}).get("file")
    if not ir:
        return None
    requested = _swap_window_suffix(ir, window)
    return _first_existing(_raw(requested), _raw(ir))


# ---------------------------------------------------------------------------
# Cheap stereo pan fallback for spatial overlays (used when the native SAF
# binaural lib isn't built). location.y is +right per ui/src/payload.js.
# ---------------------------------------------------------------------------
_PAN_FULL_SCALE_M = 2.4  # EXT_SOURCE_OFFSET_M in payload.js — maps to hard L/R


def _pan_to_stereo(mono, pan):
    """Constant-power pan a mono signal. pan in [-1, 1] (-1 left, +1 right)."""
    pan = float(np.clip(pan, -1.0, 1.0))
    angle = (pan + 1.0) * (np.pi / 4.0)  # 0..pi/2
    left = mono * np.cos(angle)
    right = mono * np.sin(angle)
    return np.stack([left, right], axis=1).astype(np.float32)


def _try_engine_transform(file_path, location, velocity):
    """Attempt the engine's Doppler+binaural transform; return stereo@TARGET_SR.

    Returns None on ANY failure (missing native SAF lib, no ffmpeg, etc.) so the
    caller can fall back. Enabling real binaural later is just building the lib;
    no code change here.
    """
    try:
        tdir = os.path.join(_ENGINE_ROOT, "transform")
        if tdir not in sys.path:
            sys.path.insert(0, tdir)
        spec = importlib.util.spec_from_file_location(
            "cranbrook_transform", os.path.join(tdir, "transform.py")
        )
        tmod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(tmod)

        speed = float(np.linalg.norm([velocity.get("x", 0), velocity.get("y", 0), velocity.get("z", 0)]))
        direction = (velocity.get("x", 1.0) or 1.0, velocity.get("y", 0.0), velocity.get("z", 0.0))
        initial = (location.get("x", 0.0), location.get("y", 0.0), location.get("z", 0.0))
        stereo, sr = tmod.transform(file_path, initial_pos=initial, direction=direction, speed=speed or 1.0)

        if sr != TARGET_SR:  # transform outputs 48 kHz; bring it back to canonical
            from scipy.signal import resample
            n = int(stereo.shape[0] * TARGET_SR / sr)
            stereo = np.stack([resample(stereo[:, 0], n), resample(stereo[:, 1], n)], axis=1)
        return stereo.astype(np.float32)
    except Exception as e:  # noqa: BLE001 — intentional broad guard; spatial is best-effort
        print(f"[engine_adapter] spatial transform unavailable, using pan fallback: {e}")
        return None


# ---------------------------------------------------------------------------
# Track builders
# ---------------------------------------------------------------------------
def _load_norm(path):
    """Load a file as mono @TARGET_SR, normalized to the reference RMS."""
    audio, _ = load_wav(path)
    return normalize_rms(audio, SPEECH_RMS_DB)


def _overlay_track(overlay):
    """Build one (audio, offset_s, gain_db) tuple from a UI overlay, or None."""
    name = overlay.get("name")
    rel = SOUND_FILE_MAP.get(name)
    if not rel:
        print(f"[engine_adapter] overlay '{name}' has no mapped sample, skipping")
        return None
    path = _raw(rel)
    if not os.path.exists(path):
        print(f"[engine_adapter] mapped file missing for '{name}': {path}, skipping")
        return None

    gain_db = float(overlay.get("gain", 0.0))
    offset = float(overlay.get("offset", 0.0))
    location = overlay.get("location")
    velocity = overlay.get("velocity")

    if location:
        stereo = None
        if velocity:  # moving source: try real Doppler + HRTF
            stereo = _try_engine_transform(path, location, velocity)
        if stereo is None:  # fallback: constant-power pan from lateral position
            mono = _load_norm(path)
            pan = float(location.get("y", 0.0)) / _PAN_FULL_SCALE_M
            stereo = _pan_to_stereo(mono, pan)
        return (stereo, offset, gain_db)

    # Non-spatial (global ambient) overlay: plain mono track.
    return (_load_norm(path), offset, gain_db)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def generate_from_payload(req, scenario):
    """Generate one mixed WAV from a /generate payload using the real engine.

    Params:
        req: the parsed JSON request body from POST /generate.
        scenario: the loaded scenario dict (from load_scenario).

    Returns:
        (wav_path, meta) — same shape backend/app.py already returns.
    """
    scenario_id = scenario["scenario_id"]
    driving = int(req.get("driving", 0))
    window = int(req.get("window", 0))
    venting = int(req.get("venting", 0))
    
    synth_dir = os.path.join(_REPO_ROOT, "synthetic")
    meta_dir = os.path.join(_REPO_ROOT, "metadata")
    os.makedirs(synth_dir, exist_ok=True)
    os.makedirs(meta_dir, exist_ok=True)

    ns = noise_superimposition(_DATA_ROOT, fs=48000)
    
    audio_list = []
    
    noise = ns.get_noise(
        speed=driving,
        window=window,
        mics=None,
        use_correction_gains=False,
    )
    audio_list.append(noise)

    if venting != 0:
        ventilation = ns.get_ventilation(
            level=venting,
            window=window,
            mics=None,
            use_correction_gains=False,
        )
        audio_list.append(ventilation)
    
    matched_components = noise_superimposition.match_duration(
        audio_list,
        fs=ns.fs,
    )

    audio_superimposed = np.sum(np.stack(matched_components, axis=0), axis=0)

    out_name = f"{scenario_id}_speed{driving}_window{window}_vent{venting}.wav"
    out_path = os.path.join(synth_dir, out_name)
    
    sf.write(out_path, audio_superimposed, ns.fs)

    meta = {
        "file": out_name,
        "scenario_id": scenario_id,
        "sample_rate": ns.fs,
        "channels": int(audio_superimposed.shape[1]) if audio_superimposed.ndim == 2 else 1,
        "duration_sec": float(audio_superimposed.shape[0] / ns.fs),
        "driving": driving,
        "window": window,
        "venting": venting,
        "use_correction_gains": False,
        "engine": "hatci-noise-superimposition",
    }

    meta_name = f"{scenario_id}_speed{driving}_window{window}_vent{venting}.json"
    meta_path = os.path.join(meta_dir, meta_name)
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    
    return out_path, meta

# def generate_from_payload(req, scenario):
#     """Generate one mixed WAV from a /generate payload using the real engine.

#     Params:
#         req: the parsed JSON request body from POST /generate.
#         scenario: the loaded scenario dict (from load_scenario).

#     Returns:
#         (wav_path, meta) — same shape backend/app.py already returns.
#     """
#     mix_audio = _load_mixer().mix_audio

#     sid = scenario["scenario_id"]
#     snr_db = float(req.get("snr_db", 5))
#     position = req.get("speaker_position", "driver")
#     seed = int(req.get("seed", 42))
#     driving = int(req.get("driving", 0))
#     window = int(req.get("window", 0))
#     venting = int(req.get("venting", 0))
#     overlays = req.get("overlays", []) or []

#     np.random.seed(seed)
#     ingredients = scenario.get("audio_ingredients", {})

#     # --- Target speech (the thing ASR must hear), optionally run through the IR
#     speech_rel = ingredients["target_speech"]["file"]
#     speech = _load_norm(_raw(speech_rel))
#     ir_path = _resolve_cabin_ir(scenario, window)
#     if ir_path:
#         ir, _ = load_wav(ir_path)
#         speech = apply_cabin_ir(speech, ir)

#     tracks = [(speech, 0.0, 0.0)]
#     noise_inputs = []

#     # --- Scenario-declared background noise (if any), at the requested SNR
#     if "background_noise" in ingredients:
#         bn = _raw(ingredients["background_noise"]["file"])
#         if os.path.exists(bn):
#             tracks.append((_load_norm(bn), 0.0, -snr_db))
#             noise_inputs.append(bn)

#     # --- Road noise selected by the UI speed/window sliders
#     road = _select_road_noise(driving, window)
#     if road:
#         tracks.append((_load_norm(road), 0.0, -snr_db))
#         noise_inputs.append(road)

#     # --- Ventilation noise selected by the UI vent/window sliders
#     vent = _select_ventilation(venting, window)
#     if vent:
#         tracks.append((_load_norm(vent), 0.0, -snr_db - 3))  # vents sit a touch below road noise
#         noise_inputs.append(vent)

#     # --- Competing speech (distractor), slightly offset
#     if "competing_speech" in ingredients:
#         comp = _raw(ingredients["competing_speech"]["file"])
#         if os.path.exists(comp):
#             tracks.append((_load_norm(comp), float(np.random.uniform(0.0, 1.0)), -snr_db))
#             noise_inputs.append(comp)

#     # --- UI overlays (gain/offset always; spatial via transform or pan)
#     overlays_applied = []
#     for ov in overlays:
#         t = _overlay_track(ov)
#         if t:
#             tracks.append(t)
#             overlays_applied.append(ov.get("name"))

#     # --- Clip length is driven by the TARGET SPEECH (this is an ASR stress
#     # test — the speech defines the window). The engine's mix_audio trims every
#     # longer noise/overlay track to this length, matching the original pipeline.
#     speech_dur = len(speech) / TARGET_SR
#     duration = max(speech_dur, 2.0) + 0.5

#     # --- Run the REAL engine mix, then guard the peak
#     mixed = mix_audio([duration] + tracks, target_sr=TARGET_SR)
#     mixed = prevent_clipping(mixed)

#     # --- Write audio + metadata where app.py serves them from
#     out_name = f"{sid}_snr{int(snr_db)}_{position}_d{driving}w{window}v{venting}_seed{seed}.wav"
#     synth_dir = os.path.join(_REPO_ROOT, "synthetic")
#     meta_dir = os.path.join(_REPO_ROOT, "metadata")
#     os.makedirs(synth_dir, exist_ok=True)
#     os.makedirs(meta_dir, exist_ok=True)
#     out_path = os.path.join(synth_dir, out_name)
#     sf.write(out_path, mixed, TARGET_SR)

#     meta = {
#         "file": out_name,
#         "scenario_id": sid,
#         "snr_db": snr_db,
#         "sample_rate": TARGET_SR,
#         "channels": int(mixed.ndim == 2 and mixed.shape[1] or 1),
#         "duration_sec": float(duration),
#         "seed": seed,
#         "speaker_position": position,
#         "driving": driving,
#         "window": window,
#         "venting": venting,
#         "speech_input": _raw(speech_rel),
#         "noise_inputs": noise_inputs,
#         "cabin_ir": ir_path or "",
#         "overlays_applied": overlays_applied,
#         "engine": "cranbrook-mixer",
#         "generated_at": datetime.now().isoformat(),
#     }
#     with open(os.path.join(meta_dir, out_name.replace(".wav", ".json")), "w") as f:
#         json.dump(meta, f, indent=2)
#     return out_path, meta
